#!/usr/bin/node

let url = process.argv[2];

if (!url) {
  console.log("Usage: ./wikp <url>")
  process.exit(1);
}

let request = require("request");

const jsdom = require("jsdom");
const { JSDOM } = jsdom;

request(url, function(_error, _response, body) {
  let { document } = (new JSDOM(body)).window;

  let paragraphs = document.querySelectorAll("p");
  let references = document.querySelectorAll(".reference");

  references.forEach(function(reference) {
    reference.remove();
  });

  paragraphs.forEach(function(paragraph) {
    console.log(paragraph.textContent);
  });
});
